import StepContainer from '@components/atoms/StepContainer';
import StepsContainer from '@components/molecules/StepsContainer';
import './Setup.css';

const SetupPage = () => {

    return (
        <main id='Setup-Utility-Main'>
            <section className='Setup-Utility-Left-Container'>
                <StepsContainer>
                    {[
                        'Getting Started',
                        'Configuring Domains',
                        'Connecting to GitHub',
                        'Secret Keys (autogenerated)'
                    ].map((title, index) => (
                        <StepContainer key={index} title={title} />
                    ))}
                </StepsContainer>
            </section>

            <section className='Setup-Utility-Container'>
                <h3 className='Setup-Utility-Header-Title'>Deploying your Quantum instance.</h3>
            </section>
        </main>
    );
};

export default SetupPage;